package org.engcia
 
import org.engcia.meiaChallenge1Team4.model.FactCF;
import org.engcia.meiaChallenge1Team4.model.Evidence;
import org.engcia.meiaChallenge1Team4.model.Hypothesis;
import org.engcia.meiaChallenge1Team4.listeners.TrackingAgendaListener
import org.engcia.meiaChallenge1Team4.model.Conclusion;

//PROJETO

rule "r1:Preco Prioritário"
@CF(1.00)
lock-on-active true
when
	Evidence( description == Evidence.PRECO_PRIORITARIO, value == "true" )
then
	Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.PRIORIDADE_PRECO, "true");
	$h.update();
end

rule "r2:Consumo Prioritário"
@CF(1.00)
lock-on-active true
when
	//Evidence( description == Evidence.PRECO_PRIORITARIO, value == "false" )
	Evidence( description == Evidence.CONSUMO_PRIORITARIO, value == "true" )
then
	Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.PRIORIDADE_CONSUMO, "true");
	$h.update();
end

rule "r3:Design Prioritário"
@CF(1.00)
lock-on-active true
when
    //Evidence( description == Evidence.PRECO_PRIORITARIO, value == "false" )
	Evidence( description == Evidence.CONSUMO_PRIORITARIO, value == "false" )
then
	Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.PRIORIDADE_DESIGN, "true");
	$h.update();
end

rule "r4:Mais Quilometragem"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.PRIORIDADE_PRECO, value == "true")
		Evidence( description == Evidence.QUAL_O_PRECO, value == "false" )
		Evidence( description == Evidence.ANTIGUIDADE_QUILOMETRAGEM, value == "false" )
	then
        Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.MAIS_QUILOMETRAGEM, "true");
    	$h.update();
end

rule "r5:Mais Antigo"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.PRIORIDADE_PRECO, value == "true")
		Evidence( description == Evidence.QUAL_O_PRECO, value == "false" )
        Evidence( description == Evidence.ANTIGUIDADE_QUILOMETRAGEM, value == "true" )
	then
        Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.MAIS_ANTIGO, "true");
        $h.update();
end

rule "r6:Imposto Relevante"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.MAIS_ANTIGO, value == "true")
		Evidence( description == Evidence.IMPOSTO_VEICULO, value == "true" )
	then
	    Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO01, "true");
        $c.update();
end

rule "r7:Imposto Nao Relevante"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.MAIS_ANTIGO, value == "true")
		Evidence( description == Evidence.IMPOSTO_VEICULO, value == "false" )
	then
	    Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO02, "true");
        $c.update();
end

rule "r8:Estado Veiculo Relevante"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.MAIS_QUILOMETRAGEM, value == "true")
		Evidence( description == Evidence.ESTADO_VEICULO, value == "true" )
	then
	    Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO03, "true");
        $c.update();
end

rule "r9:Estado Veiculo Nao Relevante"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.MAIS_QUILOMETRAGEM, value == "true")
		Evidence( description == Evidence.ESTADO_VEICULO, value == "false" )
	then
	    Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO04, "true");
        $c.update();
end

rule "r10:Mais 10 Mil - Consumo"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.PRIORIDADE_PRECO, value == "true")
		//Evidence( description == Evidence.QUAL_O_PRECO, value == "true" )
		Evidence( description == Evidence.CONSUMO_PRIORITARIO, value == "true" )
	then
	    Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.PRIORIDADE_CONSUMO, "true");
	    $h.update();
end

rule "r11:Mais 10 Mil - Design"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.PRIORIDADE_PRECO, value == "true")
		//Evidence( description == Evidence.QUAL_O_PRECO, value == "true" )
		Evidence( description == Evidence.CONSUMO_PRIORITARIO, value == "false" )
	then
	    Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.PRIORIDADE_DESIGN, "true");
        $h.update();
end

rule "r12:Combustiveis Fosseis"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.PRIORIDADE_CONSUMO, value == "true")
		Evidence( description == Evidence.COMBUSTIVEIS_FOSSEIS, value == "true" )
	then
		Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.COMBUSTIVEIS_FOSSEIS, "true");
        $h.update();
end

rule "r13:Carro Eletrico"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.PRIORIDADE_CONSUMO, value == "true")
		Evidence( description == Evidence.COMBUSTIVEIS_FOSSEIS, value == "false" )
	then
		Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.CARRO_ELETRICO, "true");
        $h.update();
end

rule "r14:Carro Gasoleo"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.COMBUSTIVEIS_FOSSEIS, value == "true")
		Evidence( description == Evidence.MEDIA_CONSUMO, value == "true" )
	then
		Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.CARRO_GASOLEO, "true");
        $h.update();
end

rule "r15:Carro Gasolina"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.COMBUSTIVEIS_FOSSEIS, value == "true")
		Evidence( description == Evidence.MEDIA_CONSUMO, value == "false" )
	then
		Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.CARRO_GASOLINA, "true");
        $h.update();
end

rule "r16:Emissoes Nao Relevantes"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.CARRO_GASOLEO, value == "true")
		Evidence( description == Evidence.EMISSOES, value == "true" )
	then
	    Conclusion $c = (Conclusion) TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO05, "true");
        $c.update();
end

rule "r17:Emissoes Nao Relevantes"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.CARRO_GASOLEO, value == "true")
		Evidence( description == Evidence.EMISSOES, value == "false" )
	then
	    Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO06, "true");
        $c.update();
end

rule "r18:Performance Relevante"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.CARRO_GASOLINA, value == "true")
		Evidence( description == Evidence.PERFORMANCE, value == "true" )
	then
	    Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO07, "true");
        $c.update();
end

rule "r19:Performance Nao Relevante"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.CARRO_GASOLINA, value == "true")
		Evidence( description == Evidence.PERFORMANCE, value == "false" )
	then
	    Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO08, "true");
        $c.update();
end

rule "r20:Carro Eletrico Mais 200km Diário - Piloto Automatico"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.CARRO_ELETRICO, value == "true")
		Evidence( description == Evidence.MAIS_200KM, value == "true" )
		Evidence( description == Evidence.PILOTO_AUTOMATICO, value == "true" )
	then
	    Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO10, "true");
        $c.update();
end

rule "r21:Carro Eletrico Mais 200km Diário - Piloto Automatico"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.CARRO_ELETRICO, value == "true")
		Evidence( description == Evidence.MAIS_200KM, value == "true" )
		Evidence( description == Evidence.PILOTO_AUTOMATICO, value == "false" )
	then
	    Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO11, "true");
        $c.update();
end

rule "r22:Carro Eletrico Menos 200km Diário - Sem Carregamento Diario"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.CARRO_ELETRICO, value == "true")
		Evidence( description == Evidence.MAIS_200KM, value == "false" )
		Evidence( description == Evidence.CARREGAMENTO_DIÁRIO, value == "false" )
	then
	    Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO09, "true");
        $c.update();
end

rule "r23:Carro Eletrico Menos 200km Diário - Sem Carregamento Diario - Piloto Automatico"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.CARRO_ELETRICO, value == "true")
		Evidence( description == Evidence.MAIS_200KM, value == "false" )
		Evidence( description == Evidence.CARREGAMENTO_DIÁRIO, value == "true" )
		Evidence( description == Evidence.PILOTO_AUTOMATICO, value == "true" )
	then
	    Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO10, "true");
        $c.update();
end

rule "r24:Carro Eletrico Menos 200km Diário - Sem Carregamento Diario -  Sem Piloto Automatico"
@CF(1.00)
lock-on-active true
	when
		Hypothesis( description == Hypothesis.CARRO_ELETRICO, value == "true")
		Evidence( description == Evidence.MAIS_200KM, value == "false" )
		Evidence( description == Evidence.CARREGAMENTO_DIÁRIO, value == "true" )
		Evidence( description == Evidence.PILOTO_AUTOMATICO, value == "false" )
	then
	    Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO11, "true");
        $c.update();
end

rule "r25:Carro Versatil"
@CF(1.00)
lock-on-active true
    when
	    Hypothesis( description == Hypothesis.PRIORIDADE_DESIGN, value == "true")
	    Evidence( description == Evidence.CARRO_VERSATIL, value == "true" )
    then
	    Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.PERFIL_VERSATIL, "true");
	    $h.update();
end

rule "r26:Carro Desportivo"
@CF(1.00)
lock-on-active true
    when
	    Hypothesis( description == Hypothesis.PRIORIDADE_DESIGN, value == "true")
	    //Evidence( description == Evidence.CARRO_VERSATIL, value == "false" )
	    Evidence( description == Evidence.CARRO_FAMILIAR, value == "false" )

    then
	    Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.PERFIL_DESPORTIVO, "true");
	    $h.update();
end

rule "r27:Carro Familiar"
@CF(1.00)
lock-on-active true
    when
	    Hypothesis( description == Hypothesis.PRIORIDADE_DESIGN, value == "true")
	    //Evidence( description == Evidence.CARRO_VERSATIL, value == "false" )
	    Evidence( description == Evidence.CARRO_FAMILIAR, value == "true" )

    then
	    Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.PERFIL_FAMILIAR, "true");
	    $h.update();
end

rule "r28:SUV Off Road"
@CF(1.00)
lock-on-active true
    when
	    Hypothesis( description == Hypothesis.PERFIL_VERSATIL, value == "true")
	    Evidence( description == Evidence.TIPO_SUV_OFF_ROAD, value == "true" )
    then
    	Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO13, "true");
	    $c.update();
end

rule "r29:SUV On Road"
@CF(1.00)
lock-on-active true
    when
	    Hypothesis( description == Hypothesis.PERFIL_VERSATIL, value == "true")
	    Evidence( description == Evidence.TIPO_SUV_OFF_ROAD, value == "false" )
    then
    	Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO12, "true");
	    $c.update();
end

rule "r30:Familiar 7 Lugares"
@CF(1.00)
lock-on-active true
    when
	    Hypothesis( description == Hypothesis.PERFIL_FAMILIAR, value == "true")
	    Evidence( description == Evidence.FAMILIAR_7_LUGARES, value == "true" )
    then
    	Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.FAMILIAR_7LUGARES, "true");
	    $h.update();
    	Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO17, "true");
	    $c.update();
end

rule "r31:Familiar 4-5 Lugares"
@CF(1.00)
lock-on-active true
    when
	    Hypothesis( description == Hypothesis.PERFIL_FAMILIAR, value == "true")
	    Evidence( description == Evidence.FAMILIAR_7_LUGARES, value == "false" )
    then
    	Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.FAMILIAR_45LUGARES, "true");
	    $h.update();
    	Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO18, "true");
	    $c.update();
end

rule "r32:Desportivo 2 portas"
@CF(1.00)
lock-on-active true
    when
	    Hypothesis( description == Hypothesis.PERFIL_DESPORTIVO, value == "true")
	    Evidence( description == Evidence.DESPORTIVO_2PORTAS, value == "true" )
    then
	    Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.DESPORTIVO_2PORTAS, "true");
	    $h.update();
end

rule "r33:Desportivo Cabrio"
@CF(1.00)
lock-on-active true
    when
	    Hypothesis( description == Hypothesis.PERFIL_DESPORTIVO, value == "true")
	    Evidence( description == "DESPORTIVO_CABRIO", value == "true" )
    then
    	Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO14, "true");
	    $c.update();
end

rule "r34:Desportivo Cabrio"
@CF(1.00)
lock-on-active true
    when
	    Hypothesis( description == Hypothesis.PERFIL_DESPORTIVO, value == "true")
	    Evidence( description == Evidence.DESPORTIVO_CABRIO, value == "false" )
    then
    	Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO15, "true");
	    $c.update();
end

rule "r35:Desportivo 4-5 Portas"
@CF(1.00)
lock-on-active true
    when
	    Hypothesis( description == Hypothesis.PERFIL_DESPORTIVO, value == "true")
	    Evidence( description == Evidence.DESPORTIVO_2PORTAS, value == "false" )
    then
    	Hypothesis $h = (Hypothesis)TrackingAgendaListener.getFactRef(Hypothesis.class, Hypothesis.DESPORTIVO_45PORTAS, "true");
	    $h.update();
    	Conclusion $c = (Conclusion)TrackingAgendaListener.getFactRef(Conclusion.class, Conclusion.TIPO16, "true");
	    $c.update();
end